name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore QueryMasterTester.csproj

      - name: Publish win-x64
        run: dotnet publish QueryMasterTester.csproj -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:DebugType=None /p:DebugSymbols=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QueryMasterTester-win-x64
          path: bin/Release/net9.0-windows/win-x64/publish/**

      - name: Pack NuGet
        run: dotnet pack QueryMasterTester.csproj -c Release -o out /p:PackageVersion=${{ github.run_number }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push out/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: Create GitHub Release with EXE
        uses: softprops/action-gh-release@v2
        with:
          name: Build ${{ github.run_number }}
          tag_name: build-${{ github.run_number }}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            bin/Release/net9.0-windows/win-x64/publish/QueryMasterTester.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


